INSERT INTO SUBJECT
VALUES (DEFAULT, 21, 'Tester', 'Alex', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 22, 'QA', 'Brittany', 'F');
INSERT INTO SUBJECT
VALUES (DEFAULT, 23, 'Developer', 'Charlie', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 24, 'Software Developer', 'Daniel', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 25, 'Software Engineer', 'Eric', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 26, 'Administrator', 'Frank', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 27, 'IT Support', 'Goliath', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 28, 'Marketing', 'Hank', 'M');
INSERT INTO SUBJECT
VALUES (DEFAULT, 29, 'HR', 'Iana', 'F');
INSERT INTO SUBJECT
VALUES (DEFAULT, 99, 'CEO', 'Jack', 'M');
