DROP TABLE IF EXISTS SUBJECT;
CREATE TABLE SUBJECT
(
    id   IDENTITY PRIMARY KEY,
    age  INT        NOT NULL,
    job  VARCHAR    NOT NULL,
    name VARCHAR    NOT NULL,
    sex  VARCHAR(1) NOT NULL
);
